### ISSUE TITLE
deduplicate "files" and "logs" functionality

### ISSUE THREAD

**Issue by f3flight** [adobdin/timmy#23]
We should unite files and logs func into something universal:

```
files:
    include:
    exclude:
    start:
    filenames: (passed to rsync directly)
    filelists: (files read and content fed to rsync)
```
